// This file was generated by Prisma, and assumes you have installed the following:
import { loadEnvFile } from 'node:process'
import { defineConfig } from 'prisma/config'

loadEnvFile()

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: process.env.DATABASE_URL,
    },
})
